# Generated by Django 3.0.5 on 2021-04-12 21:29

import artists.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=30)),
                ('subgenero', models.CharField(blank=True, max_length=20)),
                ('decada', models.CharField(blank=True, max_length=20)),
                ('canciones', djongo.models.fields.ArrayField(model_container=artists.models.CancionArtista, model_form_class=artists.models.CancionArtistaForm)),
            ],
        ),
    ]
