# Generated by Django 3.0.5 on 2021-04-12 21:29

from django.db import migrations
import djongo.models.fields
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('metadata', djongo.models.fields.EmbeddedField(model_container=songs.models.Metadata, model_form_class=songs.models.MetadataForm)),
                ('canción', djongo.models.fields.ArrayField(model_container=songs.models.Cancion, model_form_class=songs.models.CancionForm)),
            ],
        ),
    ]
